- name: Lint
  run: |
    if [ -f "eslint.config.mjs" ] || [ -f "eslint.config.js" ] || [ -f "eslint.config.cjs" ] \
       || [ -f ".eslintrc.json" ] || [ -f ".eslintrc.js" ] || [ -f ".eslintrc.cjs" ] \
       || [ -f ".eslintrc.yaml" ] || [ -f ".eslintrc.yml" ]; then
      # 扁平設定時，明確帶 --config 最穩
      if [ -f "eslint.config.mjs" ]; then
        npx eslint . --ext .js,.ts,.tsx --config eslint.config.mjs
      else
        npx eslint . --ext .js,.ts,.tsx
      fi
    else
      echo "No ESLint config found; skipping lint."
    fi
